### PR TITLE
Bug fix with case-insensitive handle lookup [fixes 1005]

### LINKED ISSUE #1005: Blank page when user profile fails to load because of case-insensitive handle lookup
From [ch2556](https://app.clubhouse.io/learnersguild/story/2556)

---

To reproduce:
1. Identify a user with both capital and lower case letters in their github handle
2. attempt to view the user's profile page in echo by using all lowercase letters in their handle in the URL (ex: for a user `MixedCase`, visit `echo.learnersguild.org/users/mixedcase`

Expected Result: user's page loads successfully
Actual Result: main content area is blank

### PR DESCRIPTION
**Pull request by Anasauce**
Fixes #1005.

## Overview

- made changes in the container component userDetail page for MixedCase and lowercase handles to match identifier in url

## Data Model / DB Schema Changes

no changes

## Environment / Configuration Changes

no changes

### CODE REVIEW

File: src/common/containers/UserDetail/index.jsx [hunk 1]
```diff
@@ -83,6 +83,7 @@ function mapStateToProps(state, ownProps) {
 
   const userSummary = Object.values(userSummariesByUserId).find(userSummary => {
     return userSummary.user && (
+      userSummary.user.handle.toLowerCase() === identifier ||
       userSummary.user.handle === identifier ||
```
Comment (prattsj) [inline src/common/containers/UserDetail/index.jsx]: No need for two checks; convert both `userSummary.user.handle` and `identifier` to lowercase and make one comparison.
