### PR TITLE
Fixes "unique key" warning for member.handle link

### LINKED ISSUE #707: Selectable table rows are not links
All the clickable elements on https://game.learnersguild.org/projects/ are not links. This means you cannot (for example) cmd-click on them to open in a new tab or right-click to do many link related actions. Please don't use onClick and instead use a real link. 

:)

---

Applies to tables in the following views:
- Users (`/users`)
- Projects (`/projects`)
- Chapters (`/chapters`)

### PR DESCRIPTION
**Pull request by sdweber422**
Fixes #707 

## Overview

When ProjectList would render, a warning stating that a unique key should be provided appeared. A new key has been implemented using a `key=project name-member handle` format.

## Data Model / DB Schema Changes

None.

## Environment / Configuration Changes

None.

## Notes

None.

### CODE REVIEW

File: src/common/containers/ProjectList/index.jsx [hunk 1]
```diff
@@ -54,7 +54,8 @@ class ProjectListContainer extends Component {
       const projectURL = `/projects/${project.name}`
       const memberHandles = (project.members || []).map(member => {
         const memberURL = `/users/${member.handle}`
-        return <Link key={member.handle} to={memberURL}>{member.handle}</Link>
+        const linkKey = `${project.cycle.cycleNumber}-${member.handle}`
```
Comment (prattsj) [inline src/common/containers/ProjectList/index.jsx]: @sdweber422: in theory, it's possible for a user to be in multiple projects in the same cycle. instead, let's make the key this: `PROJECT_NAME-MEMBER_HANDLE`.
