### PR TITLE
Fixes bug with retrospective announcements [fixes 908]

### LINKED ISSUE #908: Notification of retrospective surveys not received for cycle 49
**Overview:**
When the `/cycle reflect` command is issued, retrospective surveys should be generated for every project in a phase where `hasRetrospective=true`. Notifications should also be posted in slack in the phase channel and as DMs sent to all members of each project in the phase.

For cycle 49, no notifications were received of retrospective surveys being ready for submission.

**Notes:**
- Looks like retro surveys _were_ generated, so the issue appears to just be with the slack notifications.

**Links:**
- https://app.clubhouse.io/learnersguild/story/3639/retros-didn-t-get-formed-for-cycle-49

### PR DESCRIPTION
**Pull request by Anasauce**
Fixes #908.

## Overview

 - Users in phases with retrospectives get DM announcement
 - Channel rooms for phases with retrospective get announcement
 - Adds test coverage for worker function `processCycleReflectionStarted()`

## Data Model / DB Schema Changes

no changes to database

## Environment / Configuration Changes

no changes

### CODE REVIEW

File: src/server/actions/sendCycleReflectionAnnouncements.js [hunk 1]
```diff
@@ -26,8 +25,8 @@ async function _sendAnnouncementToPhaseChannel(cycle, phase, message) {
 
 async function _sendAnnouncementToPhaseMembers(cycle, phase, message) {
   const chatService = require('src/server/services/chatService')
-
-  const phaseProjects = Project.filter({phaseId: phase})
+  const phaseProjects =
+    await Project.filter({phaseId: phase.id})
```
Comment (prattsj) [inline src/server/actions/sendCycleReflectionAnnouncements.js]: Why split onto two lines? :)
