### PR TITLE
Fix channelId being undefined when setting channel topic.

### LINKED ISSUE #950: Goal channel topics not being set
When project goal channels are created, the topic should also be set. Currently, this isn't working.

Found in the worker logs:
```
Jul 10 09:14:40 game app/worker.1:  Channel create error: { [APIError: API Error 500 (channel_not_found) trying to invoke API (url = 'https://slack.com/api/channels.setTopic')] 
Jul 10 09:14:40 game app/worker.1:  projectCreated job 310 (attempt=1) failed: APIError: API Error 500 (channel_not_found) trying to invoke API (url = 'https://slack.com/api/channels.setTopic') 
```

### PR DESCRIPTION
**Pull request by ian-deans**
Fixes #950 .

## Overview

Echo is using a 3rd party tool, cache-manager, to wrap a Map containing the channel names and IDs that is built from data received from the Slack API. It then uses this cached Map to serve the channel IDs to setChannelTopic(). 

It seemed that the cache-manager would keep the Map in cache, and if there was no Map, it would then call the function that queries Slack API and returns the Map. But when attempting to pull and ID from the Map using a channel name that is not in it, the Map would simply return undefined and not update the data from Slack. This is what was causing errors to be thrown when attempting to set the channel topic. 

getChannelId now sets the channel values by using memoryCache.set() and returns the desired id directly from memoryCache. If the channel name is not found it refreshes it's data from Slack.

## Data Model / DB Schema Changes

none

## Environment / Configuration Changes

none

## Notes

For this scenario ( setting a channel topic for a channel just created during project initialization  ) it seems like the cached list will never have the desired channel data since each channel is created as needed. If the project belongs to a Slack channel that already exists, setChannelTopic is never called. It is only called when creating a new channel that is needed by the project currently being initialized, and the list will always need to be updated.

### CODE REVIEW

File: src/server/services/chatService/cache.js [hunk 1]
```diff
@@ -15,8 +15,11 @@ export async function getUserId(userHandle) {
 }
 
 export async function getChannelId(channelName) {
-  const channelIdMap = await _getChannelIdMap()
-  return channelIdMap.get(channelName)
+  return memoryCache.wrap(channelName, async () => {
+    const channelMap = await _getChannelIdMapUncached()
+    await Promise.each(channelMap.keys(), name => memoryCache.set(name, channelMap.get(name)))
```
Comment (ian-deans) [inline src/server/services/chatService/cache.js]: Ok awesome, yeah I think I put myself in a corner in trying to preserve as much of the pre-existing code. I would definitely prefer to rewrite the bulk of this file.
