### PR TITLE
Fixes resolveStartOfWeek for cycles (or other) started after Thursday 11:59pm

### LINKED ISSUE #1063: Week value potentially incorrect for some cycles
There was a period during which cycles were often launched on a Friday. So the values in the "Week" column of the Projects view in the web UI would be inaccurate for those cycles as it would display the Monday of the previous cycle's week.

We can assume that any cycle started on a Fri, Sat or Sun should be considered to be for the week ahead and display the following Monday's date for the "Week" (starting) value.

Related: https://github.com/LearnersGuild/echo/pull/1049/files

screen shot 2017-07-27 at 11 31 58 am

### PR DESCRIPTION
**Pull request by sdweber422**
Fixes #1063 

## Overview

'Week' in projectList view was incorrect in instances where cycle (or other) was started on a Friday. Logic was placed in the resolver to account for this. Additionally, the start of the current week is returned for any missing startTimestamp data.

## Data Model / DB Schema Changes

None.

## Environment / Configuration Changes

None.

## Notes

None.

### CODE REVIEW

File: src/server/graphql/resolvers/index.js [hunk 1]
```diff
@@ -155,7 +155,18 @@ export async function resolveProjectUserSummaries(projectSummary, args, {rootVal
 }
 
 export function resolveStartOfWeek(parent) {
-  return parent.weekStartedAt || moment(parent.startTimestamp).startOf('isoweek').toDate()
+  if (parent.weekStartedAt) {
+    return parent.weekStartedAt
+  }
+  if (!parent.startTimestamp) {
+    return moment().startOf('isoweek').toDate()
```
Comment (prattsj) [inline src/server/graphql/resolvers/index.js]: If the parent doesn't have a `startTimestamp` value, let's use the `createdAt` value.

File: src/server/graphql/resolvers/__tests__/resolveStartOfWeek.test.js [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+describe(testContext(__filename), function () {
+  before(function () {
+    this.emptyCycle = {}
+    this.cycle = {}
+    this.previousCycle = {}
+    this.nextCycle = {}
+    this.cycle.startTimestamp = '2017-07-27' // Thursday
+    this.nextCycle.startTimestamp = '2017-07-28' // Friday
+    this.previousCycle.weekStartedAt = '2017-07-17'
```
Comment (prattsj) [inline src/server/graphql/resolvers/__tests__/resolveStartOfWeek.test.js]: Why not include in the original object literals? E.g.
```js
  this.cycle = {startTimestamp: '2017-07-27'}
  this.previousCycle = {weekStartedAt: '2017-07-17'}
  this.nextCycle = {startTimestamp: '2017-07-28'}
```

Comment (prattsj) [inline src/server/graphql/resolvers/__tests__/resolveStartOfWeek.test.js]: Also note that while this might work for the tests, it's not testing quite the same behavior as the real system has -- `startTimestamp` values are dates rather than strings.

File: src/server/graphql/resolvers/__tests__/resolveStartOfWeek.test.js [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+  })
+
+  describe('when provided date is a Friday, Saturday, or Sunday', function () {
+    it('should return the date of the following Monday', function () {
+      const startOfWeek = moment(this.nextCycle.startTimestamp).startOf('isoweek').toDate()
+      const startOfNextWeek = moment(this.nextCycle.startTimestamp).startOf('isoweek').add(7, 'days').toDate()
+      const resolvedStartOfWeek = resolveStartOfWeek(this.nextCycle)
+
+      expect(resolvedStartOfWeek).to.not.eql(startOfWeek)
+      expect(resolvedStartOfWeek).to.eql(startOfNextWeek)
```
Comment (prattsj) [inline src/server/graphql/resolvers/__tests__/resolveStartOfWeek.test.js]: It's sufficient to make just one of these assertions or the other. :)

File: src/server/graphql/resolvers/__tests__/resolveStartOfWeek.test.js [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+      const startOfWeek = moment(this.cycle.startTimestamp).startOf('isoweek').toDate()
+      const startOfNextWeek = moment(this.cycle.startTimestamp).startOf('isoweek').add(7, 'days').toDate()
+      const resolvedStartOfWeek = resolveStartOfWeek(this.cycle)
+
+      expect(resolvedStartOfWeek).to.eql(startOfWeek)
+      expect(resolvedStartOfWeek).to.not.eql(startOfNextWeek)
+    })
+  })
+
+  describe('when provided date is a Friday, Saturday, or Sunday', function () {
```
Comment (prattsj) [inline src/server/graphql/resolvers/__tests__/resolveStartOfWeek.test.js]: We should separately test all 3.
